# DEPRECATED: This file is no longer used in the course.
# version: 3

# Services = containers 
# docker build -t nodejs-app .
# docker run -p 3000:3000 nodejs-app
services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"

# volumes
# docker volume create nodejs-app-data
volumes:
  nodejs-app-data:
    driver: local

# networks
# docker network create nodejs-app-network
networks:
  nodejs-app-network:
    driver: bridge
  